### ISSUE TITLE
Support Python 3?

### ISSUE THREAD

**Issue by terapyon** [collective/collective.saconnect#3]
I want to use on Plone 5.2 by Python 3. Do it support Python 3?

**Comment by terapyon** [comment]
I'm trying to support Python 3.
https://github.com/collective/collective.saconnect/tree/support-py3

Please help me with any comments.

**Comment by terapyon** [comment]
I got some errors,

```
Failure in test test_body_set (collective.saconnect.tests.test_gs.TestGS)
Traceback (most recent call last):
  File "/opt/python36/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python36/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/terapyon/dev/plone/plone521/buildout-cache/eggs/Products.GenericSetup-2.0.1-py3.6.egg/Products/GenericSetup/testing.py", line 94, in test_body_set
    self.assertEqual(adapted.body, self._BODY)
  File "/opt/python36/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python36/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: b'<?xml version="1.0" encoding="utf-8"?>\[110 chars]s>\n' != '<?xml version="1.0"?>\n<connections>\n <[92 chars]s>\n'
```

**Comment by mamico** [comment]
you could try:

```
diff --git a/src/collective/saconnect/tests/test_gs.py b/src/collective/saconnect/tests/test_gs.py
index d90cd39..6299de7 100644
--- a/src/collective/saconnect/tests/test_gs.py
+++ b/src/collective/saconnect/tests/test_gs.py
@@ -10,8 +10,8 @@ from zope.interface import directlyProvides
 import unittest
 
 
-TESTBODY = '''\
-<?xml version="1.0"?>
+TESTBODY = b'''\
+<?xml version="1.0" encoding="utf-8"?>
 <connections>
  <connection name="bar" string="eggs"/>
  <connection name="foo" string="spam"/>
```
